
/*
CREATE DATABASE [Cars]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cars', FILENAME = N'/var/opt/mssql/data/Cars.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cars_log', FILENAME = N'/var/opt/mssql/data/Cars.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Cars] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Cars] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Cars] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Cars] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Cars] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Cars] SET ARITHABORT OFF 
GO
ALTER DATABASE [Cars] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Cars] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Cars] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Cars] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Cars] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Cars] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Cars] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Cars] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Cars] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Cars] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Cars] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Cars] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Cars] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Cars] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Cars] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Cars] SET  READ_WRITE 
GO
ALTER DATABASE [Cars] SET RECOVERY FULL 
GO
ALTER DATABASE [Cars] SET  MULTI_USER 
GO
ALTER DATABASE [Cars] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Cars] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Cars] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Cars]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Cars]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Cars] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
*/
USE [Cars]
GO
CREATE SCHEMA [Sales] AUTHORIZATION [dbo]
Go

USE [Cars]
GO
CREATE SCHEMA [Maintenance] AUTHORIZATION [dbo]
Go

USE [Cars]
GO
CREATE SCHEMA [Staff] AUTHORIZATION [dbo]
Go

CREATE TABLE [staff].[tblStaffDetails]
	(
			[StaffID] int identity(1,1) PRIMARY KEY,
			[firstName] nvarchar(100) NOT NULL,
			[lastName] nvarchar(100) NOT NULL
	)
INSERT INTO Staff.tblStaffDetails(FirstName, lastName) VALUES
('Michael', 'Harrington'),
('Paul', 'Simons'),
('Dave', 'Stern')

CREATE TABLE [Sales].[tblCarDetails]
	(
			[CarID] int identity(1,1) PRIMARY KEY,
			[vinNumber] nvarchar(255) NOT NULL,
			[numberOfDoors] nvarchar(10) NOT NULL
	)
INSERT INTO Sales.tblCarDetails(vinNumber, numberOfDoors) VALUES
('00001AB', '4'),
('00007AS', '3'),
('00006AT', '3'),
('00004AY', '4'),
('00002AJ', '1')

CREATE TABLE [Maintenance].[tblBuildingMaintenance]
	(
			[maintenance] int identity(1,1) PRIMARY KEY,
			[buildingID] int NOT NULL,
			[fault] nvarchar(500) NOT NULL
	)
INSERT INTO Maintenance.tblBuildingMaintenance(BuildingID, fault) VALUES
('1', 'Blown light'),
('2', 'Blocked toilet'),
('3', 'Broken door'),
('4', 'Broken windwo')


SELECT * FROM Maintenance.tblBuildingMaintenance

DELETE FROM Maintenance.tblBuildingMaintenance

USE [master]
GO
CREATE LOGIN [Mary] WITH PASSWORD=N'ComplexP@ssw0rd', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

GO
CREATE LOGIN [Mike] WITH PASSWORD=N'veryComplexP@ssw0rd', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

USE [Cars]
GO
CREATE USER [Mary] FOR LOGIN [Mary] WITH DEFAULT_SCHEMA=[dbo]
GO

